name: events-scraper
on:
  schedule:
    - cron: "0 */1 * * *"
  workflow_dispatch: # Allows manual trigger from the Actions tab

jobs:
  fetch_m3u8_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install curl_cffi httpx pytz python-dateutil beautifulsoup4

      - name: Run Python Script
        run: |
          curl -o daddylive-events.py "${{ secrets.DADDYLIVE_EVENTS_URL }}"
          python daddylive-events.py

      - name: Commit and push changes
        run: |
          git config --global user.name "actions-user"
          git config --global user.email "actions@github.com"
          git add daddylive-events.m3u8
          git diff --staged --quiet || git commit -m "Update events"
          git push --force
         
        
